### ISSUE TITLE
Want to use this for procedural ThreeJS material parameters

### ISSUE THREAD

**Issue by bhouston** [unconed/shadergraph#10]
I'm in the midst of rewriting the ThreeJS to be [more mathematically oriented around BRDFs](https://github.com/mrdoob/three.js/pull/7324).  One aspect that I would like to address would be to allow for pluggable procedural textures into the various material slots (diffuseColor, specularColor, glossiness, etc.)  I was thinking that shadergraph would be perfect for this, because procedural textures into these slots are very similar to the graphs you are producing and are snippet-based.

I need to have snippets for various noise functions, texture samplers, combiners, etc.  I've got most of these in GLSL already.

But I do not want to use shader graph for the core of the shader -- just like in Maya or 3DS Max.  You use shader graphs to specify the inputs to a material, but the material itself tends to be a big block with slots.  There will be a ton of code within the big material that deals with all the light types of geometry processing and all that which does not change.  For me to convert the big block to a shadergraph is likely not worth the effort - it will be so specific and tailor made that no one really should need to change it.

So what is the best approach to do this?

This is what I have for nodes:

![image](https://cloud.githubusercontent.com/assets/588541/10468573/cc20a998-71cd-11e5-925f-947dc7cf76dc.png)

PS. I contribute snippets for worley, simplex, etc. noise and other type of combiner functions here if you want.  It will be very specific to shader graphs for 3D games and visual effects though.

**Comment by bhouston** [comment]
Basically I want to declare a bunch of attributes and varyings and possibly other globals (I have constructed global state, the struct GeometricContext in my PR) that are available to the snippets and then create the nodes using that context, but the those graphs compile to a function per material slot that I then call from the existing big block of code.  One graph per material is fine if it can have multiple slots as the result -- multiple functions declared, one per slot.  Thus filling out the procedural inputs to the material.

**Comment by unconed** [comment]
Not sure what you're asking here.

**Comment by bhouston** [comment]
I would like to build something akin to UE4's material inputs system:

https://docs.unrealengine.com/latest/INT/Engine/Rendering/Materials/MaterialInputs/index.html

You have uber materials (visible on the right hand side in these pictures) that are composed of fairly complex code, lots of functions behind the scenes that generally are not editable (just like UE4 physical material), but I would like to provide flexibility to users via allowing them to create shadergraphs for the inputs to that uber material (just like UE4.)

**Comment by unconed** [comment]
Well I take it you've seen MathBox? That's pretty much what it does, both for geometry and materials. I have a style, vertex color, diffuse map, and then a default material shader than can be swapped out.

This base class is a "renderable" that is specialized for particular mesh types. It produces this.renders (@ in coffeescript), an array of three.js meshes with a compiled shadergraph material:
https://github.com/unconed/mathbox/blob/master/src/render/meshes/base.coffee

In Base::_vertexColor I compose a shader fragment from parts that are passed in, i.e. shader factories that hold a partial graph:
https://github.com/unconed/mathbox/blob/master/src/render/meshes/base.coffee#L93
https://github.com/unconed/mathbox/blob/master/src/render/meshes/base.coffee#L108

These end up piped/required into some shape-specific shaders. e.g. for lines:
https://github.com/unconed/mathbox/blob/master/src/render/meshes/line.coffee#L35

Resulting in e.g. this graph:
http://acko.net/files/mathbox2/iframe-shadergraph-3.html
 
The fragment shader has more complicated options, it gets a bit messy, I should probably do this with normal GLSL and #ifdef/#define instead:
https://github.com/unconed/mathbox/blob/master/src/render/meshes/base.coffee#L120
(you can add #defines dynamically with shadergraph, see readme)

Resulting graph:
http://acko.net/files/mathbox2/iframe-shadergraph-6.html

**Comment by unconed** [comment]
Btw see this for an example with multiple callback slots on one block:
http://acko.net/files/dump/shadergraph/split.html
