### ISSUE TITLE
WebGL2

### ISSUE THREAD

**Issue by SimonMeskens** [unconed/shadergraph#16]
Do you ever plan on updating this library to WebGL2, etc? I haven't seen anything to replace this library yet, but it's so old at this point I don't dare use it.

**Comment by dcunited001** [comment]
shadergraph doesn't support webgl2 and can't be easily modified to do that. its internals parse GLSL code into an AST, but the parser is locked to webgl 1.0 and can't easily be modified.

if you want to use webgl 1.0, this library works well.

**Comment by sritchie** [comment]
Looks like this might be possible, given these references:

- https://github.com/Jam3/glsl-100-to-300
- https://github.com/glslify/glslify/issues/54

**Comment by sritchie** [comment]
Closing, but see the comment above for some info and please re-open if you're interested in working on this.
