### ISSUE TITLE
PSO particle swarm optomisation

### ISSUE THREAD

**Issue by gedw99** [unconed/shadergraph#4]
Hey Steven,

i am VERY interested in the way that MathBox2 works. Really outstanding work.

I work on computational systems and also sensing systems for various projects and companies
i would love to start to use shader graph and maptbox for both visualisation & computation.
Also chip synthesis for FPGA and ASIC has some relationships to this.

the first thing i want to start using for both computation and visualising the computation is PSO. I need this for doing NILM.

https://en.wikipedia.org/wiki/Particle_swarm_optimization

could you contact me at: gedw99 AT GMAIL dot COM.

Regards

ged

**Comment by unconed** [comment]
This is not what Github is for.
