### ISSUE TITLE
How are the function call graphs made?

### ISSUE THREAD

**Issue by almereyda** [unconed/shadergraph#7]
I like the visuals once again.
Any hint about how to create similarily neat function call graphs oneself?

I've just recently learned this praxis (thanks to Ward C.) but have no experience with it yet.
See the [IRLP script call graph](http://jon.wiki.allmende.io/view/welcome-visitors/view/notebook/view/day-20150805/view/fedwiki-call).

**Comment by unconed** [comment]
https://github.com/unconed/shadergraph/tree/master/src/visualize

**Comment by unconed** [comment]
FYI there is now a raw graph usage example:

http://acko.net/files/shadergraph2/examples/graph.html

**Comment by almereyda** [comment]
Merci! I like the clickable child.
