### ISSUE TITLE
Convert to EMCAScript 6

### ISSUE THREAD

**Issue by bhouston** [unconed/shadergraph#8]
This is a pretty impressive library.  It would be nice if this was JavaScript v6 rather than CoffeeScript.

**Comment by unconed** [comment]
I don't have any plans for that right now. The CS has worked out nicely for more than a few parts.

If it's a problem of packaging, alternative builds can be added.

**Comment by amilajack** [comment]
I'm willing to PR for this. Would that be welcome?

**Comment by sritchie** [comment]
This is done now! See the master branch after I finish merging.
