### ISSUE TITLE
Compatibility with structs and array of structs?

### ISSUE THREAD

**Issue by bhouston** [unconed/shadergraph#9]
I'm currently attempting to convert part of ThreeJS to use structs for its lighting information and likely other things.  It basically allows for high level types to be passed between nodes, rather than always just vectors, matrices or single values.

What is the ease of using structs with this library?

**Comment by unconed** [comment]
The glsl-parser module it uses does not seem to support them at all, I could never get it to work. It's picky in other ways too (e.g. reserved keywords). So that's a no.

**Comment by bhouston** [comment]
I think the solution is to extend glsl-parser to fix this issue.
